### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by aeeq** [macronut/ghostcp#44]
```
[log=2]
[ttl=12]
[mss=512]
[method=w-md5]
[server=127.0.0.1:53]
[ipv6=false]
[method=w-md5]
[method=w-md5,filter]
[method=s-seg,w-md5,https]
[method=w-md5,https,mode2]
[method=ttl]
[method=w-md5]
[method=ttl]
Service Start
panic: runtime error: slice bounds out of range [:9125606337954] with capacity 1500

goroutine 5 [running]:
github.com/macronut/godivert.(*WinDivertHandle).Recv(0xc000014620)
        /home/aeeq/go/pkg/mod/github.com/macronut/godivert@v0.0.0-20200223163208-e0ee08361ab9/windivert.go:141 +0x1c5
github.com/macronut/ghostcp/header.TCPDaemon.func1()
        /home/aeeq/src/ghostcp/ghostcp-0.5.8/header/tcp.go:518 +0x10f
created by github.com/macronut/ghostcp/header.TCPDaemon
        /home/aeeq/src/ghostcp/ghostcp-0.5.8/header/tcp.go:510 +0x437
```

**Comment by UnCLAS-Prommer** [comment]
Do you have the WinDivert.dll in the folder where the exe file is?

**Comment by macronut** [comment]
godirvert is forked from williamfhe/godivert, this type of error may be that you are using the wrong version of WinDivert.

https://github.com/macronut/ghostcp/issues/42
