### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by d0j1a1701** [macronut/ghostcp#52]
编译正常，放到 release 里并放置了 v1.4.3 的 x86_64 WinDivert.dll。

日志如下：
```
2023/08/22 17:33:42 tcp.go:515: The system cannot find the file specified. outbound and tcp.DstPort == 443
2023/08/22 17:33:42 tcp.go:515: The system cannot find the file specified. outbound and tcp.DstPort == 80
2023/08/22 17:33:42 udp.go:391: The system cannot find the file specified. outbound and udp.DstPort == 443
2023/08/22 17:33:42 tcp.go:123: The system cannot find the file specified. inbound and tcp.SrcPort == 443 and (tcp.DstPort < 5)
2023/08/22 17:33:42 tcp.go:515: The system cannot find the file specified. outbound and ip.DstAddr = 8.8.8.8 and tcp.DstPort == 53
2023/08/22 17:33:42 tcp.go:123: The system cannot find the file specified. inbound and ip.SrcAddr = 8.8.8.8 and tcp.SrcPort == 53 and (tcp.DstPort < 5)
2023/08/22 17:33:42 udp.go:31: The system cannot find the file specified. outbound and udp.DstPort == 53
Service Start
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00001e8f0?)
        C:/Program Files/Go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0x6c8c80?)
        C:/Program Files/Go/src/sync/waitgroup.go:116 +0x4b
github.com/macronut/ghostcp/header.Wait(...)
        F:/工具/实用工具/ghostcp/header/ghostcp.go:674
main.StartService()
        F:/工具/实用工具/ghostcp/main.go:88 +0x4f2
main.main()
        F:/工具/实用工具/ghostcp/main.go:175 +0x554
```

**Comment by jonm58** [comment]
WinDivert-1.4.3-A的x86_64能用

**Comment by jonm58** [comment]
你是不是没有[default.conf](https://github.com/macronut/ghostcp/blob/master/release/default.conf)？

**Comment by macronut** [comment]
WinDivert is not just a dll, please make sure it contains a sys file.
